project_id = "vpiwfabbzaebfkadmmgd"

[functions.geocode-search]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.create-cadet-user]
verify_jwt = true

[functions.toggle-user-status]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.process-email-queue]
verify_jwt = false

[functions.email-queue-webhook]
verify_jwt = false

[functions.update-task-status-after-email]
verify_jwt = false