project_id = "kdksbhapzsknieizubvu"

[functions.email-queue-webhook]
verify_jwt = false

[functions.bulk-import-contacts]
verify_jwt = true

[functions.delete-contact]
verify_jwt = true

[functions.create-parent-user]
verify_jwt = false

[functions.create-judge-user]
verify_jwt = false

[functions.create-school-admin]
verify_jwt = false

[functions.generate-template-from-pdf]
verify_jwt = true

[functions.generate-competition-placements]
verify_jwt = false
