project_id = "vpiwfabbzaebfkadmmgd"

[functions.process-email-queue]
verify_jwt = false

[functions.test-smtp-connection]
verify_jwt = false

[functions.email-queue-webhook]
verify_jwt = false

[functions.manual-process-emails]
verify_jwt = false