project_id = "vpiwfabbzaebfkadmmgd"

[functions.email-queue-webhook]
verify_jwt = false

[functions.bulk-import-contacts]
verify_jwt = true

[functions.delete-contact]
verify_jwt = true

[functions.create-parent-user]
verify_jwt = false

[functions.create-judge-user]
verify_jwt = false